ignore:
  - vulnerability: GHSA-5j98-mcp5-4vw2
    include-aliases: true
    reason: glob upgraded to 10.5.0 in package.json, but Node.js 22.20.0-alpine3.22 is still using glob 10.4.5
  - vulnerability: CVE-2025-46394
    reason: No fixes to busybox apk available as of 2025-10-16 on Dockerfile base image 22.20.0-alpine3.22
  - vulnerability: CVE-2024-58251
    reason: No fixes to busybox apk available as of 2025-10-16 on Dockerfile base image 22.20.0-alpine3.22
  - vulnerability: CVE-2025-56200
    include-aliases: true
    reason: No fixes available as of 2025-10-16 on validator npm package
  - vulnerability: CVE-2025-60876
    include-aliases: true
    reason: "Alpine base image package (apk): busybox - no npm fix available as of 2026-02-06 (moderate severity)"
  - vulnerability: GHSA-34x7-hfp2-rc4v
    include-aliases: true
    reason: "tar 6.2.1/7.4.3 bundled inside npm in Node.js Docker image (node:22.22.0-alpine3.23) - not an application dependency, no npm fix available as of 2026-02-10"
  - vulnerability: GHSA-r6q2-hw4h-h46w
    include-aliases: true
    reason: "tar 6.2.1/7.4.3 bundled inside npm in Node.js Docker image (node:22.22.0-alpine3.23) - not an application dependency, no npm fix available as of 2026-02-10"
  - vulnerability: GHSA-8qq5-rm4j-mr97
    include-aliases: true
    reason: "tar 6.2.1/7.4.3 bundled inside npm in Node.js Docker image (node:22.22.0-alpine3.23) - not an application dependency, no npm fix available as of 2026-02-10"
output:
  - table
  - json
search:
  scope: squashed
quiet: false
check-for-app-update: false
